name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, intl
        coverage: xdebug
        tools: cs2pr

    - name: Install Composer dependencies
      run: composer install

    - name: Run PHP CS Fixer
      run: |
        vendor/bin/php-cs-fixer fix --dry-run --diff
      continue-on-error: true

    - name: Annotate PHP CS Fixer output
      if: failure()
      run: |
        vendor/bin/cs2pr

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit
      
    - name: Display test coverage
      if: success()
      run: |
        vendor/bin/phpcoverage

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: tests/_output/
